# Generated by Django 4.2.17 on 2025-01-16 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soundboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundboards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Track', max_length=100)),
                ('file_url', models.URLField()),
                ('volume', models.FloatField(default=1.0)),
                ('pan', models.FloatField(default=0.0)),
                ('loop_start', models.FloatField(default=0.0)),
                ('loop_end', models.FloatField(blank=True, null=True)),
                ('loop', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('reversed', models.BooleanField(default=False)),
                ('pitch', models.FloatField(default=1.0)),
                ('solo', models.BooleanField(default=False)),
                ('mute', models.BooleanField(default=False)),
                ('soundboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='soundboard.soundboard')),
            ],
        ),
    ]
